# cell_mappers_data/__init__.py
"""Импорты данных маппингов"""

from .workshop1_box import (
    STATIC_CELLS as WORKSHOP1_BOX_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP1_BOX_DYNAMIC
)
from .workshop1_pallet import (
    STATIC_CELLS as WORKSHOP1_PALLET_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP1_PALLET_DYNAMIC
)
# noinspection SpellCheckingInspection
from .workshop1_noweight import (
    STATIC_CELLS as WORKSHOP1_NOWEIGHT_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP1_NOWEIGHT_DYNAMIC
)
from .workshop1_multitype import (
    STATIC_CELLS as WORKSHOP1_MULTITYPE_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP1_MULTITYPE_DYNAMIC
)
from .workshop2_box import (
    STATIC_CELLS as WORKSHOP2_BOX_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP2_BOX_DYNAMIC
)
from .workshop2_pallet_list import (
    STATIC_CELLS as WORKSHOP2_PALLET_LIST_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP2_PALLET_LIST_DYNAMIC
)
from .workshop2_multitype import (
    STATIC_CELLS as WORKSHOP2_MULTITYPE_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP2_MULTITYPE_DYNAMIC
)
from .workshop1_multitype_noweight import (
    STATIC_CELLS as WORKSHOP1_MULTITYPE_NOWEIGHT_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP1_MULTITYPE_NOWEIGHT_DYNAMIC
)
from .workshop1_box_noweight import (
    STATIC_CELLS as WORKSHOP1_BOX_NOWEIGHT_STATIC,
    DYNAMIC_SECTIONS as WORKSHOP1_BOX_NOWEIGHT_DYNAMIC
)

__all__ = [
    'WORKSHOP1_BOX_STATIC',
    'WORKSHOP1_BOX_DYNAMIC',
    'WORKSHOP1_PALLET_STATIC',
    'WORKSHOP1_PALLET_DYNAMIC',
    'WORKSHOP1_NOWEIGHT_STATIC',
    'WORKSHOP1_NOWEIGHT_DYNAMIC',
    'WORKSHOP1_MULTITYPE_STATIC',
    'WORKSHOP1_MULTITYPE_DYNAMIC',
    'WORKSHOP2_BOX_STATIC',
    'WORKSHOP2_BOX_DYNAMIC',
    'WORKSHOP2_PALLET_LIST_STATIC',
    'WORKSHOP2_PALLET_LIST_DYNAMIC',
    'WORKSHOP2_MULTITYPE_STATIC',
    'WORKSHOP2_MULTITYPE_DYNAMIC',
    'WORKSHOP1_MULTITYPE_NOWEIGHT_STATIC',
    'WORKSHOP1_MULTITYPE_NOWEIGHT_DYNAMIC',
    'WORKSHOP1_BOX_NOWEIGHT_STATIC',
    'WORKSHOP1_BOX_NOWEIGHT_DYNAMIC',
]